---
name: Checks

on:
  workflow_dispatch: # enables `manual` triggering on GHA page
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Login to DH
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Test
      - name: Test
        #run: docker compose run --rm app "python manage.py test"
        run: docker-compose run --rm app sh -c "source /py/bin/activate && python manage.py test"

      # Run Linting
      - name: Lint with flake8
        run: docker compose run --rm app "flake8"
