---
name: Checks

on:
  workflow_dispatch: # enables `manual` triggering on GHA page
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Login to DH
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up caching for Python dependencies
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements.dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Build and Test
      - name: Build and Test
        #run: docker compose run --rm app "python manage.py test"
        run: docker compose up --build --abort-on-container-exit app
        env:
          DJANGO_SETTINGS_MODULE: app.settings
          DATABASE_URL: sqlite://:memory:

      # Run Linting
      - name: Lint with flake8
        run: docker compose run --rm app "flake8"
